import type { PortfolioData } from '@/types'

export const DEFAULT_DATA: PortfolioData = {
  hero: {
    name: 'Alex Morgan',
    title: 'Full Stack Developer & Designer',
    subtitle: 'I craft elegant digital experiences that merge technical precision with creative vision.',
    cta_primary_text: 'View My Work',
    cta_primary_link: '#projects',
    cta_secondary_text: 'Get in Touch',
    cta_secondary_link: '#contact',
    avatar_url: '',
    available_for_work: true,
  },
  about: {
    bio: "I'm a full-stack developer with a deep love for clean code and purposeful design. I specialize in building modern web applications that are performant, accessible, and beautifully crafted. With experience spanning startups to enterprise, I bring both technical depth and creative clarity to every project.",
    tagline: 'Building tomorrow\'s web, one line at a time.',
    location: 'San Francisco, CA',
    email: 'hello@alexmorgan.dev',
    phone: '+1 (555) 000-0000',
    github_url: 'https://github.com',
    linkedin_url: 'https://linkedin.com',
    twitter_url: 'https://twitter.com',
    resume_url: '#',
    profile_image_url: '',
  },
  education: [
    {
      id: 1,
      degree: 'B.Sc. Computer Science',
      institution: 'Stanford University',
      year_start: '2019',
      year_end: '2023',
      grade: '3.92 GPA — Dean\'s List',
      description: 'Specialized in Human-Computer Interaction and Distributed Systems. President of the ACM student chapter. Thesis on real-time collaborative editing algorithms.',
      logo_url: '',
      order_index: 0,
    },
    {
      id: 2,
      degree: 'High School Diploma',
      institution: 'Lincoln Academy',
      year_start: '2015',
      year_end: '2019',
      grade: 'Valedictorian',
      description: 'Graduated top of class. Founded the school\'s first competitive programming club. State champion in Science Olympiad.',
      logo_url: '',
      order_index: 1,
    },
  ],
  projects: [
    {
      id: 1,
      title: 'NexaCloud Platform',
      description: 'Enterprise-grade SaaS platform for team collaboration. Built real-time document editing, video calling, and AI-powered task management for 10,000+ users.',
      tech_stack: ['Next.js', 'TypeScript', 'PostgreSQL', 'Redis', 'WebRTC'],
      live_url: 'https://example.com',
      github_url: 'https://github.com',
      image_url: '',
      featured: true,
      category: 'SaaS Platform',
      order_index: 0,
    },
    {
      id: 2,
      title: 'ArtFlow Mobile',
      description: 'Cross-platform mobile app for digital artists. Integrated AI-powered style transfer and real-time cloud sync. 50k+ downloads on launch.',
      tech_stack: ['React Native', 'Python', 'TensorFlow', 'AWS S3'],
      live_url: 'https://example.com',
      github_url: 'https://github.com',
      image_url: '',
      featured: true,
      category: 'Mobile App',
      order_index: 1,
    },
    {
      id: 3,
      title: 'DataViz Engine',
      description: 'Open-source visualization library with 60+ chart types, WebGL acceleration, and a React-native plugin ecosystem. 2.4k GitHub stars.',
      tech_stack: ['TypeScript', 'D3.js', 'WebGL', 'React'],
      live_url: 'https://example.com',
      github_url: 'https://github.com',
      image_url: '',
      featured: false,
      category: 'Open Source',
      order_index: 2,
    },
  ],
  skills: [
    { id: 1, name: 'React / Next.js', level: 95, category: 'Frontend', order_index: 0 },
    { id: 2, name: 'TypeScript',      level: 92, category: 'Frontend', order_index: 1 },
    { id: 3, name: 'CSS / Tailwind',  level: 90, category: 'Frontend', order_index: 2 },
    { id: 4, name: 'Node.js',         level: 88, category: 'Backend',  order_index: 3 },
    { id: 5, name: 'Python / Django', level: 84, category: 'Backend',  order_index: 4 },
    { id: 6, name: 'PostgreSQL',      level: 82, category: 'Backend',  order_index: 5 },
    { id: 7, name: 'Docker / K8s',    level: 76, category: 'DevOps',   order_index: 6 },
    { id: 8, name: 'AWS / GCP',       level: 79, category: 'DevOps',   order_index: 7 },
    { id: 9, name: 'Figma / Design',  level: 85, category: 'Design',   order_index: 8 },
  ],
  experience: [
    {
      id: 1,
      role: 'Senior Frontend Engineer',
      company: 'TechCorp Inc.',
      year_start: '2023',
      year_end: 'Present',
      description: 'Led complete redesign of the core product UI, improving user engagement by 43% and reducing churn by 18%. Architected a component library used across 6 product teams. Mentored 4 junior engineers.',
      tech_used: ['React', 'TypeScript', 'GraphQL', 'Storybook'],
      company_url: 'https://example.com',
      logo_url: '',
      order_index: 0,
    },
    {
      id: 2,
      role: 'Full Stack Developer',
      company: 'StartupXYZ',
      year_start: '2022',
      year_end: '2023',
      description: 'Third engineering hire. Built the entire mobile web experience from scratch. Owned backend APIs serving 100k+ daily active users. Reduced API latency by 60% through caching strategies.',
      tech_used: ['Vue.js', 'Django', 'PostgreSQL', 'AWS'],
      company_url: 'https://example.com',
      logo_url: '',
      order_index: 1,
    },
  ],
  contact: {
    heading: "Let's Build Something",
    subheading: "Have a project in mind, want to collaborate, or just want to say hello? My inbox is always open.",
    email: 'hello@alexmorgan.dev',
    phone: '+1 (555) 000-0000',
    location: 'San Francisco, CA',
    calendly_url: '',
    show_form: true,
  },
  stats: {
    projects_completed: 42,
    years_experience: 4,
    happy_clients: 28,
    github_stars: 2400,
  },
}
