import type { PortfolioData } from '@/types'

export const DEFAULT_DATA: PortfolioData = {
  hero: {
    name: 'Usman Hassan',
    title: 'BS Information Technology & Full Stack Developer',
    subtitle: 'I am a passionate IT graduate and developer from Pakistan, dedicated to building meaningful digital solutions and crafting elegant user experiences.',
    cta_primary_text: 'View My Work',
    cta_primary_link: '#projects',
    cta_secondary_text: 'Get in Touch',
    cta_secondary_link: '#contact',
    avatar_url: '/image.png',
    available_for_work: true,
    cv_url: '',
  },
  about: {
    bio: "I am an IT graduate with a BS in Information Technology from Quaid e Azam University Islamabad. I am deeply passionate about creating modern web and mobile applications. Based in Islamabad, I focus on writing clean code and developing software that solves real-world problems. With a strong foundation in both frontend and backend development, along with mobile app development in Flutter, I am continuously learning and applying new technologies to build scalable, impactful solutions.",
    tagline: 'Empowering businesses through scalable IT solutions.',
    location: 'i10/1 Islamabad Pakistan',
    email: 'musmanhassan942@gmail.com',
    phone: '+92 313 0818121 / 0344 5107807',
    github_url: 'https://github.com/musmanhassan942',
    linkedin_url: '',
    twitter_url: '',
    resume_url: '#',
    profile_image_url: '/image1.png',
  },
  education: [
    {
      id: 1,
      degree: 'BS Information Technology',
      institution: 'Quaid e Azam University Islamabad',
      year_start: '2022',
      year_end: '2026',
      grade: 'Graduated',
      description: 'Focused on Software Engineering, Mobile App Development, and AI. Developed a Final Year Project involving AI-based sign language translation in collaboration with the Ministry of Planning and Development.',
      logo_url: '/uni.png',
      order_index: 0,
    },
  ],
  projects: [
    {
      id: 1,
      title: 'Sign2Text: AI Sign Language Translator (FYP)',
      description: 'An innovative AI-powered Sign Language Translation System developed as a Final Year Project in collaboration with the Ministry of Planning and Development. Designed to bridge the communication gap for the deaf community, the app uses the device camera to record sign language and translates it into real-time text and speech. Conversely, when a hearing person speaks, it converts speech to text and renders it into sign language via a realistic 3D animated model.',
      tech_stack: ['Flutter', 'Python', 'Machine Learning', '3D Modeling'],
      live_url: '',
      github_url: 'https://github.com',
      image_url: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=800&q=80',
      featured: true,
      category: 'AI / Mobile App',
      order_index: 0,
    },
    {
      id: 2,
      title: 'Multi Vendor E-Commerce App',
      description: 'A comprehensive multi-vendor marketplace mobile application. It allows various local sellers to manage their inventory and sales while providing customers with a seamless shopping, cart, and checkout experience with local payment gateways integrated.',
      tech_stack: ['Flutter', 'Dart', 'Firebase', 'Node.js'],
      live_url: '',
      github_url: 'https://github.com',
      image_url: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=800&q=80',
      featured: true,
      category: 'Mobile App',
      order_index: 1,
    },
    {
      id: 3,
      title: 'Real Estate Portal',
      description: 'A modern property listing platform for Islamabad/Rawalpindi real estate, allowing users to search, filter, and view high-quality property listings.',
      tech_stack: ['Next.js', 'Firebase', 'Tailwind CSS'],
      live_url: 'https://example.com',
      github_url: 'https://github.com',
      image_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
      featured: false,
      category: 'Web Development',
      order_index: 2,
    },
  ],
  skills: [
    { id: 1, name: 'Flutter / Dart', level: 95, category: 'Mobile', order_index: 0 },
    { id: 2, name: 'React / Next.js', level: 85, category: 'Frontend', order_index: 1 },
    { id: 3, name: 'Python / ML',      level: 80, category: 'Backend', order_index: 2 },
    { id: 4, name: 'Node.js / Express', level: 80, category: 'Backend',  order_index: 3 },
    { id: 5, name: 'Firebase',   level: 90, category: 'Database',  order_index: 4 },
    { id: 6, name: 'MySQL / PostgreSQL',level: 82, category: 'Database', order_index: 5 },
    { id: 7, name: 'Git / GitHub',    level: 88, category: 'Tools',    order_index: 6 },
    { id: 8, name: 'Figma / UI Design',level: 75, category: 'Design',  order_index: 7 },
  ],
  experience: [
    {
      id: 1,
      role: 'Mobile App Developer',
      company: 'Tech Solutions Islamabad',
      year_start: '2023',
      year_end: 'Present',
      description: 'Developing cross-platform mobile applications using Flutter. Working on integrating AI models into mobile workflows and optimizing app performance. Collaborating closely with UI/UX designers and backend engineers.',
      tech_used: ['Flutter', 'Dart', 'Firebase', 'REST APIs'],
      company_url: 'https://example.pk',
      logo_url: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=200&q=80',
      order_index: 0,
    },
    {
      id: 2,
      role: 'Freelance App Developer',
      company: 'Self-Employed',
      year_start: '2022',
      year_end: '2023',
      description: 'Provided mobile development and IT support services to small businesses in Rawalpindi and Islamabad. Created responsive e-commerce solutions and local directory apps.',
      tech_used: ['Flutter', 'Firebase', 'Dart', 'UI/UX'],
      company_url: '',
      logo_url: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=200&q=80',
      order_index: 1,
    },
  ],
  contact: {
    heading: "Let's Build Something Together",
    subheading: "Whether you have a project in mind, need a developer for your team, or just want to connect, feel free to reach out!",
    email: 'musmanhassan942@gmail.com',
    phone: '+92 313 0818121 / 0344 5107807',
    location: 'i10/1 Islamabad Pakistan',
    calendly_url: '',
    show_form: true,
  },
  stats: {
    projects_completed: 12,
    years_experience: 2,
    happy_clients: 8,
    github_stars: 45,
  },
}
